execution:
    uuid: 05c8a0c8-e504-4312-a834-64eda32d7958
    runtime:
        start: 2018-05-18T15:09:15.577425-07:00
        end: 2018-05-18T15:35:58.899995-07:00
        duration: 26 minutes, 43 seconds, and 322570 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:feature-classifier'
    action: fit_classifier_naive_bayes
    inputs:
    -   reference_reads: aeb20a7c-a545-4cde-911e-68691d52aedb
    -   reference_taxonomy: 1c374df8-641d-4975-a6df-48e14558bdfd
    -   class_weight: null
    parameters:
    -   classify__alpha: 0.01
    -   classify__chunk_size: 20000
    -   classify__class_prior: 'null'
    -   classify__fit_prior: false
    -   feat_ext__alternate_sign: false
    -   feat_ext__analyzer: char_wb
    -   feat_ext__binary: false
    -   feat_ext__decode_error: strict
    -   feat_ext__encoding: utf-8
    -   feat_ext__input: content
    -   feat_ext__lowercase: true
    -   feat_ext__n_features: 8192
    -   feat_ext__ngram_range: '[8, 8]'
    -   feat_ext__non_negative: false
    -   feat_ext__norm: l2
    -   feat_ext__preprocessor: 'null'
    -   feat_ext__stop_words: 'null'
    -   feat_ext__strip_accents: 'null'
    -   feat_ext__token_pattern: (?u)\b\w\w+\b
    -   feat_ext__tokenizer: 'null'
    -   memory: 'null'
    output-name: classifier

environment:
    platform: macosx-10.9-x86_64
    python: |-
        3.5.5 | packaged by conda-forge | (default, Feb 13 2018, 05:40:31)
        [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
    framework: 2018.2.0
    plugins:
        feature-classifier:
            version: 2018.2.0
            website: https://github.com/qiime2/q2-feature-classifier
    python-packages:
        widgetsnbextension: 3.1.3
        wheel: 0.30.0
        webencodings: '0.5'
        wcwidth: 0.1.7
        urllib3: '1.22'
        unifrac: 0.9.2
        traitlets: 4.3.2
        tornado: 4.5.3
        testpath: 0.3.1
        terminado: 0.8.1
        statsmodels: 0.8.0
        six: 1.11.0
        simplegeneric: 0.8.1
        setuptools: 38.5.1
        Send2Trash: 1.4.2
        seaborn: 0.8.1
        scipy: 0.19.1
        scikit-learn: 0.19.1
        scikit-bio: 0.5.1
        requests: 2.18.4
        qiime2: 2018.2.0
        q2templates: 2018.2.0
        q2cli: 2018.2.0
        q2-vsearch: 2018.2.0
        q2-types: 2018.2.0
        q2-taxa: 2018.2.0
        q2-sample-classifier: 2018.2.0
        q2-quality-filter: 2018.2.0
        q2-quality-control: 2018.2.0
        q2-phylogeny: 2018.2.0
        q2-metadata: 2018.2.0
        q2-longitudinal: 2018.2.0
        q2-gneiss: 2018.2.0
        q2-feature-table: 2018.2.0
        q2-feature-classifier: 2018.2.0
        q2-emperor: 2018.2.0
        q2-diversity: 2018.2.0
        q2-demux: 2018.2.0
        q2-deblur: 2018.2.0
        q2-dada2: 2018.2.0
        q2-cutadapt: 2018.2.0
        q2-composition: 2018.2.0
        q2-alignment: 2018.2.0
        pyzmq: 17.0.0
        PyYAML: '3.12'
        pytz: '2018.3'
        python-dateutil: 2.6.1
        PySocks: 1.6.8
        pyparsing: 2.2.0
        pyOpenSSL: 17.4.0
        Pygments: 2.2.0
        pycparser: '2.18'
        ptyprocess: 0.5.2
        psutil: 5.4.0
        prompt-toolkit: 1.0.15
        pip: 9.0.1
        pickleshare: 0.7.4
        pexpect: 4.4.0
        patsy: 0.5.0
        parso: 0.1.1
        pandocfilters: 1.4.1
        pandas: 0.22.0
        numpy: 1.12.1
        notebook: 5.4.0
        nose: 1.3.7
        nbformat: 4.4.0
        nbconvert: 5.3.1
        natsort: 5.0.2
        msgpack-python: 0.5.1
        mistune: 0.8.3
        matplotlib: 2.1.2
        MarkupSafe: '1.0'
        lockfile: 0.12.2
        jupyter-core: 4.4.0
        jupyter-client: 5.2.2
        jsonschema: 2.6.0
        Jinja2: '2.10'
        jedi: 0.11.1
        ipywidgets: 7.1.1
        ipython: 6.2.1
        ipython-genutils: 0.2.0
        ipykernel: 4.8.1
        idna: '2.6'
        html5lib: 1.0.1
        h5py: 2.7.0
        future: 0.16.0
        fastcluster: 1.1.24
        entrypoints: 0.2.3
        emperor: 1.0.0b13
        decorator: 4.1.2
        deblur: 1.0.3
        Cython: 0.27.3
        cutadapt: '1.15'
        cryptography: 2.1.4
        click: '6.7'
        chardet: 3.0.4
        cffi: 1.11.2
        certifi: 2018.1.18
        CacheControl: 0.12.3
        bokeh: 0.12.13
        bleach: 2.0.0
        backports.functools-lru-cache: '1.5'
        asn1crypto: 0.22.0
        appnope: 0.1.0
        biom-format: 2.1.6
        cycler: 0.10.0
        gneiss: 0.4.2
        ijson: '2.3'
        tzlocal: '1.3'
        xopen: 0.3.2
